name: ascii_camera
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  camera: ^0.10.5+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  image_picker: ^1.0.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  build_runner: ^2.3.3
  intl_utils: ^2.8.1
  freezed: ^2.4.0

flutter:
  uses-material-design: true
